name: Build Image

on: 
  workflow_dispatch:
    inputs:
      clickhouse-version:
        description: 'Clickhouse version(e.g: 22.3.3.44-lts)'
        required: true
        default: '22.3.3.44-lts'

jobs:
  build-arm64-image:
    name: Build ARM64 Image
    runs-on: [self-hosted,arm64]
    steps:
      - uses: actions/checkout@v3

      - name: Clone Clickhouse and submodules
        run: |
          git clone https://github.com/ClickHouse/ClickHouse.git
          cd ClickHouse && git checkout v${{ github.event.inputs.clickhouse-version }} && git submodule update --init --recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: knatnetwork
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push latest images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            knatnetwork/clickhouse-arm64:${{ github.event.inputs.clickhouse-version }}


  build-amd64-image:
    name: Build AMD64 Image
    runs-on: [self-hosted,amd64]
    steps:
      - uses: actions/checkout@v3

      - name: Clone Clickhouse and submodules
        run: |
          git clone https://github.com/ClickHouse/ClickHouse.git
          cd ClickHouse && git checkout v${{ github.event.inputs.clickhouse-version }} && git submodule update --init --recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: knatnetwork
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Build and push latest images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            knatnetwork/clickhouse-amd64:${{ github.event.inputs.clickhouse-version }}
  
  combine-two-images:
    runs-on: ubuntu-latest
    needs:
      - build-arm64-image
      - build-amd64-image
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: knatnetwork
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      
      - name: Combine two images
        run: |
          docker manifest create knatnetwork/clickhouse:${{ github.event.inputs.clickhouse-version }} --amend knatnetwork/clickhouse-amd64:${{ github.event.inputs.clickhouse-version }} --amend knatnetwork/clickhouse-arm64:${{ github.event.inputs.clickhouse-version }}

          docker manifest push knatnetwork/clickhouse:${{ github.event.inputs.clickhouse-version }}